spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: localhost
      port: 6379

  logging:
    level:
      root: INFO
      com.c202.userservice: DEBUG
      org.springframework.security: DEBUG
      org.springframework.data.redis: DEBUG

jwt:
  secret-key: yourVerySecretKeyHereItShouldBeAtLeast32CharactersLong
  access-token-validity-in-ms: 3600000
  refresh-token-validity-in-ms: 2592000000
  token-prefix: Bearer
  header-string: Authorization

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/