SERVER_PORT: 0

spring:
  application:
    name: guestbook-service

  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URI}

  cloud:
    config:
      fail-fast: ${SPRING_CLOUD_CONFIG_FAIL_FAST}